### ISSUE TITLE
Complexity in Implementation

### ISSUE THREAD

**Issue by shenxiul** [facebook/fbpca#1]
Hi @ajtulloch 

Thanks for your nice work! I have a question about complexity in your implementation.

In your implementation computing pca, you use

``` python
Q = mult(A, np.random.uniform(low=-1.0, high=1.0, size=(n, l)))
```

in line 1534 in fbpca.py, which leads to the computational complexity of calculating pca as O(mnk) if A is in shape m \* n and we are computing first k singular values. However in their paper [arXiv: 0909.4061](http://arxiv.org/abs/0909.4061) and another paper by same authors [Liberty, Edo, et al., PNAS 104.51 (2007): 20167-20172.](http://www.pnas.org/content/104/51/20167.short), they improved their algorithm to O(k^2(m+n) + mn\log(k)) by bypassing the multiplication directly instead. May I ask if my understanding of your implementation is correct? And should we work on improving it further to see how it works?

**Comment by tygert** [comment]
Hi! If you use any extra iterations -- that is, set n_iter > 0 in 
eigenn, eigens, and pca -- then the complexity is O(mnk). The paper of 
Liberty, Woolfe, et al. tends not to be accurate enough for data 
analysis but does indeed provide faster low-rank approximations when the 
singular values of the matrix being approximated decay rapidly. My 
personal web site provides separate software packages for the different 
applications (data analysis vs. matrix compression). Cheers, Mark

**Comment by shenxiul** [comment]
Hi @tygert,

Thanks for your explanation! Yes that's very true. If we take extra iterations the complexity is always O(mnk). So this package doesn't optimize for n_iter=0 specifically? May I also ask for the link of your personal website you mentioned?

**Comment by tygert** [comment]
fbpca is optimized for data analysis ("principal component analysis"). My personal website is http://tygert.com -- see http://tygert.com/software.html for the software. Thanks for your interest!

**Comment by tygert** [comment]
By the way, @shenxiul, if you can describe your use case, I can help guide you to an algorithm or code optimized for your particular application.

**Comment by shenxiul** [comment]
Hi @tygert,

Thanks for your generous help! In my application, our k covers almost all significant singular values, and m = n ~ k^p and the whole matrix is dense (p is some constant depend on specific use case).  If we do svd directly the reconstruction error is usually very small (1e-4 or less). If my understanding is correct, this should count into the decaying fast singular values case? That's why I want to implement the faster algorithm but I am having a hard time understand the sampled FFT algorithm in arXiv: 0909.4061, which they claimed to be O(k^2(m+n)).

To my understanding, they are decomposing the sampling matrix to Omega=DFR, but didn't specify how to perform the multiplication and cite another paper instead, which was a bit too technical to me... If they are multiplying these matrices in series, the AD part itself will be O(mn), how can that be linear in m and n? They might be doing that in other ways?

**Comment by tygert** [comment]
How does your matrix arise? How do you get its entries?

**Comment by shenxiul** [comment]
Oh sorry I made a stupid mistake, so it's indeed proportional to both m and n because the leading term is actually O(mnlog(k)). So Is my understanding correct? The way to multiply it is multiply D, F and R in series? When multiplying F there involves a Fourier transformation.

Getting the entries is a long story and involving a lot of other (I guess) irrelevant part of the whole algorithm. Why is it important?

**Comment by tygert** [comment]
Can you describe exactly which class of matrices you need to compress?

**Comment by tygert** [comment]
Usually there is a way to apply the matrix to a vector rapidly without forming all its entries.

**Comment by tygert** [comment]
How do you know that the matrix has a low rank? Are its entries smooth as a function of the row and column indices?

**Comment by tygert** [comment]
(Incidentally, you might want to continue this conversation via e-mail to mark@tygert.com rather than on GitHub.)
