### ISSUE TITLE
Distributed / Spark version

### ISSUE THREAD

**Issue by Tagar** [facebook/fbpca#6]
Thanks for sharing this! 

Was this work modeled after this article https://research.fb.com/fast-randomized-svd/ ? which mentions Spark, it doesn't look this code can run in Spark / can run distributely?

> 9.4 * 10⁷ × 4 * 10³ matrix with 1.6 * 10⁹ non-zeros, 60 seconds on single machine server vs 50 seconds on a 68 machine cluster with Spark.

**Comment by tygert** [comment]
Eventually we wrote a reasonable implementation for Spark -- see http://tygert.com/spark.pdf ... however, fbpca is still our best single-machine code (standardize on scipy's?).

**Comment by tygert** [comment]
See Remark 3 at http://tygert.com/spark.pdf

**Comment by Tagar** [comment]
Thank you @tygert ! 

Nice wrap-up in the http://tygert.com/spark.pdf (some of the math was above me though).

Your project was referenced in a comment to my question at 
https://datascience.stackexchange.com/questions/34331/distributed-pca-or-an-equivalent?noredirect=1#comment40375_34331 

Is there is a Pull Request for Apache Spark? Is there is a jira that tracks this improvement? 
We're on Spark 2.3 (and will be migrating to Spark 2.3 soon).
It seems that https://github.com/hl475/svd is based on an older version of Spark?

Would be great to have your work as a Spark package, or to have an official pull request to the Spark project so hopefully it can be accepted into core Spark soon.

Thanks!

**Comment by tygert** [comment]
@Tagar : https://github.com/hl475/svd is indeed based on an older version of Spark. Unfortunately, as the machine-learning library in Spark is supposed to be migrating to DataFrames, while the support for DataFrames is still evolving, someone else will need to implement the methods from http://tygert.com/spark.pdf for the new format. That would definitely be a valuable contribution. An alternative hack is to set parameters appropriately in a package for alternating least squares, using the observation described at http://tygert.com/als.pdf

**Comment by Tagar** [comment]
1)
Do you mind if I create a Spark jira to keep track of this improvement? It'll help to raise awareness to this issue and hopefully somebody will pick this up. 

2)
http://tygert.com/als.pdf Wow. Didn't know it's possible. Can you please reference an example that uses Spark's ALS to create a low-rank matrix approximation? ALS is very scalable. That would be great if we could do use ALS instead.

3)
Also it seems I missed your earlier comment here on SciPy
> however, fbpca is still our best single-machine code (standardize on scipy's?).

Not sure if SciPy can operate directly on a 1M(number of features) x 60M(number of rows) matrix for example (due to memory but also computational constraints). That datasize is what we normally would like to run dimensionality reduction on.
Although there are two different approaches on how to run SciPy on Spark:
1. One from Databricks - https://github.com/databricks/spark-sklearn
2. And another - https://github.com/lensacom/sparkit-learn/ 
The latter one seems have references to randomized SVD solver, e.g. https://github.com/lensacom/sparkit-learn/blob/master/splearn/decomposition/truncated_svd.py#L198

**Comment by tygert** [comment]
@Tagar :
1. Be my guest! The easiest, most efficient, and most accurate approach is to implement the pseudocode at http://tygert.com/spark.pdf
2. Implementing http://tygert.com/als.pdf from scratch is harder, less efficient, and less accurate than implementing http://tygert.com/spark.pdf -- however, if you plan on implementing alternating minimization anyways, then the hack can be convenient.
3. Scikit-learn's team spent quite a bit of effort making its randomized SVD match fbpca -- https://github.com/scikit-learn/scikit-learn/pull/5141 -- but there still remains the issue described at https://github.com/scikit-learn/scikit-learn/issues/11102
